"""Stable bounded identifiers used to label controlled synthetic cases."""

DEMO_EVENT_TYPE = "DEMO_SCENARIO_SEEDED"
DEMO_EVENT_SOURCE = "DEMO_SEED"

HIGH_VALUE_APPROVAL = "HIGH_VALUE_APPROVAL"
ALREADY_CAPTURED_PROTECTION = "ALREADY_CAPTURED_PROTECTION"
HARD_STOP_ATTENTION = "HARD_STOP_ATTENTION"

RESERVED_DEMO_SCENARIO_KEYS = frozenset(
    {
        HIGH_VALUE_APPROVAL,
        ALREADY_CAPTURED_PROTECTION,
        HARD_STOP_ATTENTION,
    }
)

__all__ = [
    "ALREADY_CAPTURED_PROTECTION",
    "DEMO_EVENT_SOURCE",
    "DEMO_EVENT_TYPE",
    "HARD_STOP_ATTENTION",
    "HIGH_VALUE_APPROVAL",
    "RESERVED_DEMO_SCENARIO_KEYS",
]
