"""Stable bounded identifiers used to label controlled synthetic cases."""

DEMO_EVENT_TYPE = "DEMO_SCENARIO_SEEDED"
DEMO_EVENT_SOURCE = "DEMO_SEED"
OFFLINE_DEMO_STRATEGY_MODEL = "arc-demo-offline-strategy-v1"

OPENAI_EVIDENCE_EVENT_TYPE = "OPENAI_EVIDENCE_CASE_CREATED"
OPENAI_EVIDENCE_EVENT_SOURCE = "OPENAI_EVIDENCE_SCRIPT"
OPENAI_EVIDENCE_SCENARIO = "OPENAI_SYNTHETIC_HIGH_VALUE"
OPENAI_EVIDENCE_CASE_REFERENCE = "openai_evidence_high_value_v1"

HIGH_VALUE_APPROVAL = "HIGH_VALUE_APPROVAL"
ALREADY_CAPTURED_PROTECTION = "ALREADY_CAPTURED_PROTECTION"
HARD_STOP_ATTENTION = "HARD_STOP_ATTENTION"

RESERVED_DEMO_SCENARIO_KEYS = frozenset(
    {
        HIGH_VALUE_APPROVAL,
        ALREADY_CAPTURED_PROTECTION,
        HARD_STOP_ATTENTION,
    }
)

__all__ = [
    "ALREADY_CAPTURED_PROTECTION",
    "DEMO_EVENT_SOURCE",
    "DEMO_EVENT_TYPE",
    "HARD_STOP_ATTENTION",
    "HIGH_VALUE_APPROVAL",
    "OFFLINE_DEMO_STRATEGY_MODEL",
    "OPENAI_EVIDENCE_EVENT_SOURCE",
    "OPENAI_EVIDENCE_EVENT_TYPE",
    "OPENAI_EVIDENCE_CASE_REFERENCE",
    "OPENAI_EVIDENCE_SCENARIO",
    "RESERVED_DEMO_SCENARIO_KEYS",
]
