"""create core persistence schema

Revision ID: 002cdbacef93
Revises:
Create Date: 2026-08-23 15:52:18.442459

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = '002cdbacef93'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchant_policies',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.String(length=100), nullable=False),
    sa.Column('automation_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allowed_actions', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('max_automated_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_contact_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('recovery_window_minutes', sa.Integer(), server_default='0', nullable=False),
    sa.Column('high_value_threshold_minor', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('require_approval_above_minor', sa.BigInteger(), nullable=True),
    sa.Column('stopping_rules', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('high_value_threshold_minor >= 0', name=op.f('ck_merchant_policies_high_value_threshold_non_negative')),
    sa.CheckConstraint('max_automated_attempts >= 0', name=op.f('ck_merchant_policies_max_automated_attempts_non_negative')),
    sa.CheckConstraint('max_contact_attempts >= 0', name=op.f('ck_merchant_policies_max_contact_attempts_non_negative')),
    sa.CheckConstraint('recovery_window_minutes >= 0', name=op.f('ck_merchant_policies_recovery_window_non_negative')),
    sa.CheckConstraint('require_approval_above_minor IS NULL OR require_approval_above_minor >= 0', name=op.f('ck_merchant_policies_approval_threshold_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_policies')),
    sa.UniqueConstraint('merchant_id', name='uq_merchant_policies_merchant_id')
    )
    op.create_table('payment_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_reference', sa.String(length=64), nullable=False),
    sa.Column('merchant_id', sa.String(length=100), nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_id', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True, comment='Amount in currency minor units'),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('current_state', sa.Enum('DETECTED', 'RECONCILING', 'DIAGNOSED', 'DECISIONED', 'POLICY_VALIDATED', 'ACTIONED', 'WAITING_FOR_OUTCOME', 'RECOVERED', 'EXHAUSTED', 'ESCALATED', name='case_state', native_enum=False, create_constraint=True, length=32), server_default='DETECTED', nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_description', sa.Text(), nullable=True),
    sa.Column('error_source', sa.String(length=100), nullable=True),
    sa.Column('error_step', sa.String(length=100), nullable=True),
    sa.Column('error_reason', sa.String(length=100), nullable=True),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount IS NULL OR amount >= 0', name=op.f('ck_payment_cases_amount_non_negative')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_payment_cases_attempt_count_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_cases')),
    sa.UniqueConstraint('case_reference', name='uq_payment_cases_case_reference')
    )
    op.create_index('ix_payment_cases_current_state', 'payment_cases', ['current_state'], unique=False)
    op.create_index('ix_payment_cases_customer_id', 'payment_cases', ['customer_id'], unique=False)
    op.create_index('ix_payment_cases_merchant_id', 'payment_cases', ['merchant_id'], unique=False)
    op.create_index('ix_payment_cases_payment_id', 'payment_cases', ['payment_id'], unique=False)
    op.create_index('ix_payment_cases_subscription_id', 'payment_cases', ['subscription_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('account_id', sa.String(length=100), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('subscription_id', sa.String(length=100), nullable=True),
    sa.Column('customer_id', sa.String(length=100), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('signature_verified', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_status', sa.Enum('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED', 'UNSUPPORTED', name='event_processing_status', native_enum=False, create_constraint=True, length=32), server_default='RECEIVED', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.CheckConstraint("payload_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_webhook_events_payload_hash_sha256_hex')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    sa.UniqueConstraint('razorpay_event_id', name='uq_webhook_events_razorpay_event_id')
    )
    op.create_index('ix_webhook_events_event_type', 'webhook_events', ['event_type'], unique=False)
    op.create_index('ix_webhook_events_payment_id', 'webhook_events', ['payment_id'], unique=False)
    op.create_index('ix_webhook_events_received_at', 'webhook_events', ['received_at'], unique=False)
    op.create_index('ix_webhook_events_subscription_id', 'webhook_events', ['subscription_id'], unique=False)
    op.create_table('case_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['payment_cases.id'], name=op.f('fk_case_events_case_id_payment_cases'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_events'))
    )
    op.create_index('ix_case_events_case_id_created_at', 'case_events', ['case_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_events_case_id_created_at', table_name='case_events')
    op.drop_table('case_events')
    op.drop_index('ix_webhook_events_subscription_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_received_at', table_name='webhook_events')
    op.drop_index('ix_webhook_events_payment_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_event_type', table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_payment_cases_subscription_id', table_name='payment_cases')
    op.drop_index('ix_payment_cases_payment_id', table_name='payment_cases')
    op.drop_index('ix_payment_cases_merchant_id', table_name='payment_cases')
    op.drop_index('ix_payment_cases_customer_id', table_name='payment_cases')
    op.drop_index('ix_payment_cases_current_state', table_name='payment_cases')
    op.drop_table('payment_cases')
    op.drop_table('merchant_policies')
    # ### end Alembic commands ###
